### ISSUE TITLE
Unexpected token } in JSON

### ISSUE THREAD

**Issue by peter-lxc** [laosb/ghos3#1]
Thanks for providing an update to this AWS S3 module but i have an issue when trying to use it and only happens when I add the storage section. For my test i added the example supplied 

ERROR Unable to find storage adapter s3 in ,/var/lib/ghost/content/adapters/,/var/lib/ghost/versions/5.44.0/core/server/adapters/.

**Comment by laosb** [comment]
Can you check you copied ghos3 to `./content/adapters/` as `s3`? Please `cd` into your `content/adapters` folder and try `ls`. You should see `s3` in it, and then `cd s3 && ls` you should see `index.js` among all other files.

**Comment by jac1013** [comment]
Probably related to: https://github.com/laosb/ghos3/issues/2

**Comment by laosb** [comment]
Likely fixed with the documentation change.
