### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by nagaame** [laosb/ghos3#19]
Hello, I used your library on my Ghost blog instance, but when using cloudflare R2 storage, my configuration kept failing and couldn't connect. Could you please help me improve my configuration?

```json
// ......

"storage": {
    "active": "s3",
    "media": {
      "adapter": "s3"
    },
    "files": {
      "adapter": "s3"
    },
    "s3": {
      "accessKeyId": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "secretAccessKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "region": "wnam",
      "bucket": "storage",
      "assetHost": "https://storage.domain.com",
      "pathPrefix": "",
      "endpoint": "https://dcexxxxxxxxxxxxxxxxxxxxxxxxxxx.r2.cloudflarestorage.com",
      "forcePathStyle": true,
      "acl": ""
    }
  }
```
I have placed all my folders in the root directory.

<img width="1341" alt="image" src="https://github.com/laosb/ghos3/assets/6214936/f3ea3eaa-0c30-4eb9-968d-9f2ef295a400">

**Comment by laosb** [comment]
According to [R2 S3 compatibility doc](https://developers.cloudflare.com/r2/api/s3/api/#bucket-region), you should specify `region` = `auto`.
