### ISSUE TITLE
Quick documentation fix that will prevent people from hitting a wall in the first try

### ISSUE THREAD

**Issue by jac1013** [laosb/ghos3#2]
Hello @laosb , thank you very much for updating this storage integration. Something that's probably "biting" everyone that tries out this library is this line:

```
cp -r ./node_modules/ghos3 ./content/adapters/storage/s3
```

That line should be:

```
cp -r ./node_modules/ghos3/* ./content/adapters/storage/s3
```

Because otherwise we end up with `./content/adapters/storage/s3/ghos3/index.js` and that is what's making the error: `but errored during boot with: Unable to find storage adapter s3 in`.

This is wrong in the original package as well.

**Comment by laosb** [comment]
Oh, that's totally my fault of not checking the command🙈

Would you like to submit a PR for this doc change?

**Comment by jac1013** [comment]
https://github.com/laosb/ghos3/pull/3
